import Vue from 'vue'
import { Button, Container, Main, Header, Footer, Menu, MenuItem, Carousel, CarouselItem,
Card, Col, Row, Divider, Breadcrumb, BreadcrumbItem,pagination,Form, FormItem,Input} from 'element-ui'

Vue.use(Button)
Vue.use(Container)
Vue.use(Main)
Vue.use(Header)
Vue.use(Footer)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(Carousel)
Vue.use(CarouselItem)
Vue.use(Card)
Vue.use(Col)
Vue.use(Row)
Vue.use(Divider)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Form)
Vue.use(FormItem)
// Vue.use(Textarea)
Vue.use(Input)
Vue.use(pagination)
// Vue.use(Button)
